name: "Update SPEC 0 dependencies"
description: "Update the lower bounds of Python dependencies covered by the Scientific Python SPEC 0 support schedule"
author: Sam Vente
inputs:
  target_branch:
    description: "Target branch for the pull request"
    required: true
    default: "main"
  project_file_name: 
    description: "Path to the project file listing dependencies, relative to repository root. Defaults to 'pyproject.toml'. Currently only pyproject.toml is supported."
    required: true
    default: "pyproject.toml"
  create_pr: 
    description: "Whether the action should open a PR or not. Set to false for dry-run/testing."
    required: true
    default: true
  schedule_path:
    description: "Path to the schedule.json file. If missing, it will be downloaded from the latest release of savente93/SPEC0-schedule"
    default: schedule.json
  token:
    description: "GitHub token with repo permissions to create pull requests"
    required: true

runs:
  using: "composite"
  permissions:
    contents: write
    pull-requests: write
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      shell: bash
      run: |
        git config user.name "GitHub Actions [bot]"
        git config user.email "github-actions-bot@users.noreply.github.com"

    - name: Download schedule artifact
      shell: bash
      env:
        SCHEDULE_FILE: ${{ inputs.schedule_path }}
      run: |
        set -e
        if [ ! -f "$SCHEDULE_FILE" ]; then
          echo "Downloading schedule.json from latest release..."
          gh release download -R "savente93/SPEC0-schedule" --pattern schedule.json -O "$SCHEDULE_FILE"
        else
          echo "Schedule file already exists at $SCHEDULE_FILE"
        fi

    - uses: prefix-dev/setup-pixi@v0.8.14
      name: Setup Pixi
      with:
        pixi-version: v0.49.0
        manifest-path: ${{ github.action_path }}/pyproject.toml

    - name: Run update script
      shell: bash
      run: |
        set -e
        echo "Updating ${{inputs.project_file_name}} using schedule ${{inputs.schedule_path}}"
        python ${{ github.action_path }}/spec0-update.py "${{ github.workspace }}/${{ inputs.project_file_name }}" "${{ inputs.schedule_path }}"
        # Clean up schedule file so it does not appear in PR
        rm "${{ inputs.schedule_path }}"

    - name: Show changes (dry-run)
      if: ${{ inputs.create_pr != 'true' }}
      shell: bash
      run: |
        echo "Dry run: showing changes that would be committed"
        git --no-pager diff

    - name: Create Pull Request
      if: ${{ inputs.create_pr == 'true' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        commit-message: "chore: Drop support for unsupported packages conform SPEC 0"
        title: "Drop support for unsupported packages conform SPEC 0"
        body: "This PR was created automatically"
        base: ${{ inputs.target_branch }}
        branch: update-spec0-dependencies-${{ github.run_id }}
