name: Test Action
on: [push, pull_request]

jobs:
  generate_data:
    runs-on: ubuntu-latest
    name: Run action on test file in repo
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate version data using local action
        uses: ./
        with: 
          project_file_name: tests/test_data/pyproject.toml
          create_pr: false
          schedule_path: tests/test_data/test_schedule.json

